#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh

# Workspace
mkdir -p $HOME/{workspace,ufcg,mestrado,corban,paneas}

# Install oh-my-zsh
if [ ! -d ~/.oh-my-zsh ]
then
  echo "Install oh my zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

if [ ! -d ~/.oh-my-zsh/custom/themes/powerlevel10k ]
then
  echo "Install powerlevel10k"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

if ! command -v nvm &> /dev/null
then
    echo "Install nvm"
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    source ~/.zshrc
fi

if ! command -v node --version &> /dev/null
then
  echo "Install node"
  nvm install --lts
fi

# Build nvim
if ! command -v nvim &> /dev/null
then
  echo "Install nvim"
  git clone git@github.com:neovim/neovim.git build/nvim
  cd $DOTFILES/build/nvim && git checkout stable && CMAKE_BUILD_TYPE=Release make && sudo make install
fi

# Backup zshrc
if [ ! -L ~/.zshrc ] && [ -f ~/.zshrc ]
then
  echo "Backup .zshrc"
  mv ~/.zshrc ~/.zshrc.bak
fi

if ! command -v yarn --version &> /dev/null
then
  echo "Enable yarn"
  corepack enable yarn
fi

if ! command -v pnpm --version &> /dev/null
then
  echo "Enable pnpm"
  corepack enable pnpm
fi

if ! command -v docker &> /dev/null
then
  echo "Install docker"
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt update
  sudo apt install -y docker-ce docker-ce-cli containerd.io
  sudo usermod -aG docker $USER
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
