#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh,git,fonts"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.files
fi

# Deps
sudo apt update
sudo apt dist-upgrade -y
sudo apt install -y zsh fzf ripgrep fd-find stow ninja-build gettext cmake \
    unzip curl tmux golang-go xclip python3-pip apt-transport-https \
    ca-certificates curl software-properties-common

curl -sSL https://install.python-poetry.org | python3 -

# Change default shell
sudo usermod --shell /bin/zsh andre

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
