#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh,git,fonts"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.files
fi

# Deps
sudo apt update
sudo apt dist-upgrade
sudo apt install -y zsh fzf ripgrep fd-find stow ninja-build gettext cmake unzip curl tmux golang-go xclip
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11 python3.11-venv python3.11-distutils

curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

pip install pipenv

# Change default shell
sudo usermod --shell /bin/zsh andre

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
