# Video
profile=gpu-hq
hwdec=auto-safe
video-sync=display-resample
interpolation=yes
tscale=oversample
deband=yes

# Audio
volume=80
volume-max=150
audio-file-auto=fuzzy

# Subtitles
sub-auto=fuzzy
slang=por,pt,eng,en
sub-font-size=42
sub-border-size=2
sub-shadow-offset=1

# Playback
save-position-on-quit=yes
resume-playback=yes
keep-open=yes

# Interface
osc=yes
osd-bar=yes
osd-duration=1500
osd-fractions=yes
force-window=yes
autofit-larger=90%x90%

# Screenshots
screenshot-format=png
screenshot-directory=~/Pictures
screenshot-template=mpv-%F-%p
