---
dotfile_links:
  - src: bin/tmux-sessionizer
    dest: .local/bin/tmux-sessionizer
  - src: nvim
    dest: .config/nvim
  - src: tmux/.tmux.conf
    dest: .tmux.conf
  - src: zsh/.zshrc
    dest: .zshrc
  - src: zsh/.p10k.zsh
    dest: .p10k.zsh
  - src: git/.gitconfig
    dest: .gitconfig
  - src: git/.gitpaneas
    dest: .gitpaneas
  - src: git/.gitpdtec
    dest: .gitpdtec
  - src: fonts
    dest: .fonts
  - src: alacritty
    dest: .config/alacritty
  - src: kitty
    dest: .config/kitty
  - src: mpv
    dest: .config/mpv
